import React, { useState, useEffect } from 'react';
import { MapContainer, TileLayer, Polyline, Marker, Popup } from 'react-leaflet';
import { supabase } from '../lib/supabase';
import { motion } from 'framer-motion';
import { toast } from 'sonner';

// Custom icons using Lucide or basic HTML since leaflet default icons often break in React without extra config
import L from 'leaflet';
const createIcon = (color) => L.divIcon({
  className: 'custom-icon',
  html: `<div style="background-color: ${color}; width: 16px; height: 16px; border-radius: 50%; border: 3px solid white; box-shadow: 0 0 10px ${color};"></div>`,
  iconSize: [16, 16],
  iconAnchor: [8, 8]
});

// Extensive mock GIS data for Indian Railways
const CORRIDOR_GIS = {
  // DB Specific Corridors generated by AI Optimizer
  'MAS-AJJ': { name: 'Chennai - Arakkonam', points: [[13.0827, 80.2707], [13.0844, 79.6672]] },
  'TVC-QLN': { name: 'Thiruvananthapuram - Kollam', points: [[8.5241, 76.9366], [8.8932, 76.6141]] },
  'LKO-CNB': { name: 'Lucknow - Kanpur', points: [[26.8467, 80.9462], [26.4499, 80.3319]] },
  'JP-AII': { name: 'Jaipur - Ajmer', points: [[26.9124, 75.7873], [26.4499, 74.6399]] },
  'NGP-BSL': { name: 'Nagpur - Bhusaval', points: [[21.1458, 79.0882], [21.0455, 75.8011]] },
  'CSMT-KYN': { name: 'Mumbai CSMT - Kalyan', points: [[18.9400, 72.8352], [19.2403, 73.1305]] },
  'PUNE-DD': { name: 'Pune - Daund', points: [[18.5204, 73.8567], [18.4636, 74.5772]] },
  'ADI-BRC': { name: 'Ahmedabad - Vadodara', points: [[23.0225, 72.5714], [22.3072, 73.1812]] },
  'ALD-MGS': { name: 'Prayagraj - Pt. Deen Dayal Upadhyaya', points: [[25.4358, 81.8463], [25.2753, 83.1186]] },
  'BZA-VSKP': { name: 'Vijayawada - Visakhapatnam', points: [[16.5062, 80.6200], [17.6868, 83.2185]] },
  'HWH-BWN': { name: 'Howrah - Bardhaman', points: [[22.5958, 88.3110], [23.2324, 87.8615]] },
  'GHY-NJP': { name: 'Guwahati - New Jalpaiguri', points: [[26.1445, 91.7362], [26.6854, 88.4239]] },
  'SBC-JTJ': { name: 'KSR Bengaluru - Jolarpettai', points: [[12.9779, 77.5670], [12.5647, 78.5630]] },
  'NDLS-GZB': { name: 'New Delhi - Ghaziabad', points: [[28.6448, 77.2167], [28.6692, 77.4538]] },
  'BPL-ET': { name: 'Bhopal - Itarsi', points: [[23.2599, 77.4126], [22.6115, 77.7618]] },

  // Background generic network connections
  'GZB-CNB': { name: 'Ghaziabad - Kanpur', points: [[28.6692, 77.4538], [26.4499, 80.3319]] },
  'CNB-PRYJ': { name: 'Kanpur - Prayagraj', points: [[26.4499, 80.3319], [25.4358, 81.8463]] },
  'DDU-PNBE': { name: 'DDU - Patna', points: [[25.2753, 83.1186], [25.5941, 85.1376]] },
  'PNBE-HWH': { name: 'Patna - Howrah', points: [[25.5941, 85.1376], [22.5958, 88.3110]] },
  'NDLS-MTJ': { name: 'New Delhi - Mathura', points: [[28.6448, 77.2167], [27.4924, 77.6737]] },
  'MTJ-KOTA': { name: 'Mathura - Kota', points: [[27.4924, 77.6737], [25.2138, 75.8648]] },
  'KOTA-RTM': { name: 'Kota - Ratlam', points: [[25.2138, 75.8648], [23.3315, 75.0367]] },
  'RTM-BRC': { name: 'Ratlam - Vadodara', points: [[23.3315, 75.0367], [22.3072, 73.1812]] },
  'BRC-ST': { name: 'Vadodara - Surat', points: [[22.3072, 73.1812], [21.1702, 72.8311]] },
  'ST-BCT': { name: 'Surat - Mumbai Central', points: [[21.1702, 72.8311], [18.9696, 72.8193]] },
  'PUNE-SUR': { name: 'Pune - Solapur', points: [[18.5204, 73.8567], [17.6599, 75.9064]] },
  'SUR-WADI': { name: 'Solapur - Wadi', points: [[17.6599, 75.9064], [17.0654, 76.9836]] },
  'WADI-GTL': { name: 'Wadi - Guntakal', points: [[17.0654, 76.9836], [15.1674, 77.3738]] },
  'GTL-MAS': { name: 'Guntakal - Chennai', points: [[15.1674, 77.3738], [13.0827, 80.2707]] },
  'NDLS-AGC': { name: 'New Delhi - Agra', points: [[28.6448, 77.2167], [27.1767, 78.0081]] },
  'AGC-JHS': { name: 'Agra - Jhansi', points: [[27.1767, 78.0081], [25.4484, 78.5685]] },
  'JHS-BPL': { name: 'Jhansi - Bhopal', points: [[25.4484, 78.5685], [23.2599, 77.4126]] },
  'ET-NGP': { name: 'Itarsi - Nagpur', points: [[22.6115, 77.7618], [21.1458, 79.0882]] },
  'BPQ-BZA': { name: 'Balharshah - Vijayawada', points: [[19.8491, 79.3516], [16.5062, 80.6200]] },
  'BZA-MAS': { name: 'Vijayawada - Chennai', points: [[16.5062, 80.6200], [13.0827, 80.2707]] }
};

export default function LiveNetworkMap() {
  const [blocks, setBlocks] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchBlocks = async () => {
      setLoading(true);
      const { data, error } = await supabase
        .from('blocks')
        .select('*')
        .in('status', ['proposed', 'approved', 'active']);
        
      if (data) {
        setBlocks(data);
      }
      setLoading(false);
    };

    fetchBlocks();

    const channel = supabase.channel('map-blocks')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'blocks' }, () => {
        fetchBlocks();
      })
      .subscribe();

    return () => supabase.removeChannel(channel);
  }, []);

  const handleBlockAction = async (blockId, newStatus) => {
    try {
      const { error } = await supabase
        .from('blocks')
        .update({ status: newStatus })
        .eq('id', blockId);

      if (error) throw error;
      
      if (newStatus === 'approved') {
        toast.success(`Block ${blockId.slice(0,4).toUpperCase()} Approved & Locked`);
      } else {
        toast.error(`Block ${blockId.slice(0,4).toUpperCase()} Rejected`);
      }
      
      // We don't need to manually fetch blocks here because the realtime 
      // postgres subscription in useEffect will automatically trigger fetchBlocks!
    } catch (err) {
      toast.error("Failed to update block status");
      console.error(err);
    }
  };

  // Map segments based on active/approved blocks
  const segments = Object.keys(CORRIDOR_GIS).map(id => {
    const gis = CORRIDOR_GIS[id];
    if (id === 'DEFAULT') return null;
    
    // Check if this corridor has an active/approved block vs proposed
    const corridorBlocks = blocks.filter(b => b.section_id === id);
    
    const activeBlocks = corridorBlocks.filter(b => b.status === 'approved' || b.status === 'active');
    const proposedBlocks = corridorBlocks.filter(b => b.status === 'proposed');
    
    const hasActive = activeBlocks.length > 0;
    const hasProposed = proposedBlocks.length > 0 && !hasActive;
    
    return {
      id,
      name: gis.name,
      points: gis.points,
      status: hasActive ? 'ACTIVE' : hasProposed ? 'PROPOSED' : 'CLEAR',
      blocks: corridorBlocks
    };
  }).filter(Boolean);

  return (
    <div className="space-y-6 animate-fadeIn h-[calc(100vh-8rem)]">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <span className="material-symbols-outlined text-blue-700">radar</span>
            Live Network & Block GIS
          </h1>
          <p className="text-sm text-slate-600 mt-1">
            Real-time geospatial visualization of active maintenance blocks and corridor health.
          </p>
        </div>
        <div className="flex gap-4 items-center bg-white/90 backdrop-blur-md px-4 py-2 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.8)]"></div>
            <span className="text-xs font-mono font-bold text-slate-700">Clear Route</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 rounded-full bg-amber-500 shadow-[0_0_8px_rgba(245,158,11,0.8)] animate-pulse"></div>
            <span className="text-xs font-mono font-bold text-slate-700">AI Proposed</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 rounded-full bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.8)]"></div>
            <span className="text-xs font-mono font-bold text-slate-700">Locked Block</span>
          </div>
        </div>
      </div>

      <motion.div 
        initial={{ opacity: 0, scale: 0.98 }}
        animate={{ opacity: 1, scale: 1 }}
        className="w-full h-full rounded-2xl overflow-hidden border-4 border-white shadow-xl relative"
      >
        {loading && (
          <div className="absolute inset-0 bg-white/50 backdrop-blur-sm z-[1000] flex items-center justify-center">
             <span className="material-symbols-outlined text-4xl text-blue-600 animate-spin">sync</span>
          </div>
        )}
        
        {/* Standard OSM with CSS inversion for dark theme without API keys */}
        <MapContainer center={[22.5937, 78.9629]} zoom={5.5} style={{ height: '100%', width: '100%' }}>
          <TileLayer
            className="dark-map-tiles"
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
          />
          
          {segments.map(seg => {
            let color = '#20658A'; // Subdued dark teal/blue for inactive routes
            let dashArray = null;
            let weight = 3;
            let opacity = 0.4; // Very dim so the network looks like a background web
            let glow = false;

            if (seg.status === 'ACTIVE') {
              color = '#ef4444'; // Red
              weight = 7;
              opacity = 1;
            } else if (seg.status === 'PROPOSED') {
              color = '#f59e0b'; // Amber
              dashArray = '10, 10';
              weight = 7;
              opacity = 1;
              glow = true;
            } else if (seg.status === 'CLEAR') {
              color = '#10b981'; // Emerald
              weight = 5;
              opacity = 0.8; // Stand out more than background if it's explicitly tracked
            }
            
            return (
              <React.Fragment key={seg.id}>
                {/* Glowing underlay for blocked/proposed sections */}
                {(seg.status === 'ACTIVE' || seg.status === 'PROPOSED') && (
                  <Polyline 
                    positions={seg.points} 
                    color={color} 
                    weight={15} 
                    opacity={0.3} 
                    className={glow ? "animate-pulse" : ""}
                  />
                )}
                <Polyline 
                  positions={seg.points} 
                  color={color} 
                  weight={weight} 
                  opacity={opacity}
                  dashArray={dashArray}
                >
                  <Popup className="font-sans">
                    <div className="p-1 min-w-[200px]">
                      <h3 className="font-bold text-slate-800">{seg.name}</h3>
                      <p className="text-xs text-slate-500 font-mono mb-2 border-b border-slate-200 pb-2">Section: {seg.id}</p>
                      
                      {seg.blocks.length > 0 ? (
                        <div className="space-y-2 max-h-[200px] overflow-y-auto">
                          {seg.blocks.map(b => (
                            <div key={b.id} className={`p-2 rounded-lg text-xs border ${
                              b.status === 'proposed' ? 'bg-amber-50 border-amber-200' : 'bg-red-50 border-red-200'
                            }`}>
                              <div className="flex justify-between items-center mb-1">
                                <strong className={b.status === 'proposed' ? 'text-amber-700' : 'text-red-700'}>
                                  {b.status.toUpperCase()}
                                </strong>
                                <span className="font-mono text-[10px] text-slate-500">BLK-{b.id.slice(0,4).toUpperCase()}</span>
                              </div>
                              <div className="text-slate-700 font-mono">
                                {new Date(b.start_time).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})} - {new Date(b.end_time).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                              </div>
                              {b.status === 'proposed' && (
                                <div className="mt-2 grid grid-cols-2 gap-2">
                                  <button 
                                    onClick={() => handleBlockAction(b.id, 'approved')}
                                    className="bg-emerald-500 text-white text-[10px] font-bold py-1 px-2 rounded hover:bg-emerald-600 transition-colors flex items-center justify-center gap-1"
                                  >
                                    <span className="material-symbols-outlined text-[12px]">check</span>
                                    Approve
                                  </button>
                                  <button 
                                    onClick={() => handleBlockAction(b.id, 'rejected')}
                                    className="bg-slate-100 text-slate-600 border border-slate-300 text-[10px] font-bold py-1 px-2 rounded hover:bg-red-50 hover:text-red-600 hover:border-red-200 transition-colors flex items-center justify-center gap-1"
                                  >
                                    <span className="material-symbols-outlined text-[12px]">close</span>
                                    Reject
                                  </button>
                                </div>
                              )}
                            </div>
                          ))}
                        </div>
                      ) : (
                        <div className="text-emerald-600 font-bold text-xs bg-emerald-50 p-2 rounded-lg border border-emerald-200">
                          Route Clear - Normal Operations
                        </div>
                      )}
                    </div>
                  </Popup>
                </Polyline>
                
                <Marker position={seg.points[0]} icon={createIcon(color)} />
                <Marker position={seg.points[1]} icon={createIcon(color)} />
              </React.Fragment>
            );
          })}
        </MapContainer>
      </motion.div>
    </div>
  );
}
